services:
  db:
    image: postgres:16-alpine
    container_name: quarkbau-monolith-db
    environment:
      POSTGRES_DB: quarkbau_monolith
      POSTGRES_USER: quarkbau
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/init-monolith-db.sql:/docker-entrypoint-initdb.d/init-monolith-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quarkbau -d quarkbau_monolith" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: quarkbau-monolith-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quarkbau_monolith
      SPRING_DATASOURCE_USERNAME: quarkbau
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_NEO4J_URI: bolt://graphdb:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    depends_on:
      db:
        condition: service_healthy
      graphdb:
        condition: service_healthy

  graphdb:
    image: neo4j:5-community
    container_name: quarkbau-monolith-graph
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:7474 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
